name: Queen D. Scott
favicon: null
layout_spectrum: 0.07511238614097238
typography_spectrum: 0.06747
title: Queen D. Scott Official Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ff9b8b'
    - '#ff4700'
    - '#5e7766'
  brandStrength: 0.4654300194233656
  lightness: 0.9375
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
