name: Queen D. Scott
favicon: null
layout_spectrum: 0.74201
typography_spectrum: 0.08666
title: Queen D. Scott Official Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ff9b8b'
    - '#ff4700'
    - '#5e7766'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
