title: Queen D. Scott Official Site
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.9121864
  brandStrength: 1
  lightness: 0.625448
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ff9b8b'
    - '#ff4700'
    - '#5e7766'
  rhythmicContrast: 0.2222222
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Queen D. Scott
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.08666
layout_spectrum: 0.74201
